"""
Git Operations — local-first, CI-safe.

FLOW CHUẨN:
  1. prepare_feature_branch()      → tạo feature branch LOCAL từ backbone (không push)
  2. commit_wip()                  → mỗi lần dev agent viết xong / retry → commit local
                                     KHÔNG push. CI không chạy.
  3. finalize_and_merge()          → khi TEST_PASS:
                                       a. squash toàn bộ WIP commits thành 1 commit sạch
                                       b. merge --no-ff vào integration/current-sprint LOCAL
                                       KHÔNG push. KHÔNG xóa feature branch.
  4. push_backbone_to_origin()     → gọi 1 lần duy nhất SAU KHI TOÀN BỘ SPRINT XONG
                                       CI chạy đúng 1 lần tại đây.
  5. delete_feature_branch()       → xóa nhánh feature MANUAL khi bạn muốn dọn dẹp

RULE:
  - Feature branch KHÔNG BAO GIỜ được push (không có push trong prepare/commit_wip/finalize)
  - Feature branch KHÔNG bị xóa tự động — giữ lại để debug/review
  - Integration branch chỉ được push sau khi TOÀN BỘ SPRINT hoàn thành
  - develop chỉ nhận merge manual sau khi sprint kết thúc (ngoài scope pipeline)
"""
import os
import subprocess
import datetime
import re

# ================================================================
REMOTE_URL = "https://github.com/gnudevx/pos-app-test_v2.git"
# Dùng token để tránh nhập password:
# REMOTE_URL = "https://ghp_YOUR_TOKEN@github.com/gnudevx/pos-app-test_v2.git"
# ================================================================

BACKBONE = "integration/current-sprint"


# ── Utilities ──────────────────────────────────────────────────────────────────

def make_branch_name(task_id: str, summary: str) -> str:
    slug = summary.lower()
    slug = re.sub(r'[^a-z0-9\s-]', '', slug)
    slug = re.sub(r'\s+', '-', slug.strip())
    slug = re.sub(r'-+', '-', slug)
    slug = slug[:40].rstrip('-')
    return f"feature/{task_id.lower()}-{slug}"


def run(cmd: str, cwd: str) -> tuple[bool, str]:
    result = subprocess.run(
        f"git {cmd}",
        shell=True, capture_output=True, text=True,
        cwd=cwd, encoding="utf-8", errors="ignore",
    )
    return result.returncode == 0, (result.stdout + result.stderr).strip()


def current_branch(repo_dir: str) -> str:
    _, stdout = run("rev-parse --abbrev-ref HEAD", repo_dir)
    return stdout.strip()


def _ensure_remote(repo_dir: str) -> bool:
    ok, stdout = run("remote get-url origin", repo_dir)
    if ok and stdout.strip():
        return True
    ok, out = run(f"remote add origin {REMOTE_URL}", repo_dir)
    if ok:
        print(f"      [git] Remote added: {REMOTE_URL}")
    else:
        print(f"      [git] Failed to add remote: {out}")
    return ok


def _has_staged_changes(repo_dir: str) -> bool:
    _, out = run("diff --cached --stat", repo_dir)
    return bool(out.strip())


def _has_any_changes(repo_dir: str) -> bool:
    _, out = run("status --porcelain", repo_dir)
    return bool(out.strip())


def _count_commits_ahead(repo_dir: str, base_branch: str, current: str) -> int:
    """Đếm số commit của current branch vượt hơn base_branch."""
    _, out = run(f"rev-list --count {base_branch}..{current}", repo_dir)
    try:
        return int(out.strip())
    except ValueError:
        return 0


# ── Init ───────────────────────────────────────────────────────────────────────

def init_repo_if_needed(repo_dir: str) -> None:
    """
    Khởi tạo repo nếu chưa có. Tạo initial commit trên develop.
    Push develop lên origin (1 lần duy nhất khi init).
    """
    os.makedirs(repo_dir, exist_ok=True)

    if not os.path.exists(os.path.join(repo_dir, ".git")):
        run("init", repo_dir)
        run('config user.email "dev-agent@pos-pipeline.local"', repo_dir)
        run('config user.name "POS Dev Agent"', repo_dir)

    result = subprocess.run(
        ["git", "log", "--oneline", "-1"],
        cwd=repo_dir, capture_output=True, text=True
    )
    if result.returncode != 0 or not result.stdout.strip():
        print("[git] Repo trống — tạo initial commit trên develop...")
        run("checkout -b develop", repo_dir)
        readme = os.path.join(repo_dir, "README.md")
        with open(readme, "w") as f:
            f.write("# POS App\nGenerated by POS Pipeline.\n")
        run("add -A", repo_dir)
        run('commit -m "chore: initial commit"', repo_dir)
        _ensure_remote(repo_dir)
        ok, out = run("push -u origin develop", repo_dir)
        if ok:
            print("[git] develop pushed to origin")
        else:
            print(f"[git] Push develop failed (ok to continue locally): {out[:200]}")
    else:
        print("[git] Repo đã có commit, bỏ qua init")
        _ensure_remote(repo_dir)


def ensure_backbone(repo_dir: str) -> None:
    """
    Đảm bảo backbone branch tồn tại LOCAL. KHÔNG push.
    Orchestrator gọi 1 lần đầu sprint, trước vòng lặp task.
    """
    ok, _ = run(f"checkout {BACKBONE}", repo_dir)
    if not ok:
        # Backbone chưa tồn tại — tạo từ develop
        run("checkout develop", repo_dir)
        run(f"checkout -b {BACKBONE}", repo_dir)
        print(f"[git] Backbone branch created: {BACKBONE}")
    else:
        print(f"[git] Backbone branch exists: {BACKBONE}")
    # Quay về develop để orchestrator tiếp tục
    run("checkout develop", repo_dir)


# ── Feature branch lifecycle ───────────────────────────────────────────────────

def prepare_feature_branch(repo_dir: str, branch_name: str) -> None:
    """
    Tạo feature branch LOCAL từ đầu mút mới nhất của backbone.
    KHÔNG push lên remote — CI không chạy.

    Nếu branch đã tồn tại (retry sau crash): reset về backbone để bắt đầu sạch.
    """
    # Đảm bảo backbone tồn tại
    ok, _ = run(f"rev-parse --verify {BACKBONE}", repo_dir)
    if not ok:
        ensure_backbone(repo_dir)

    run(f"checkout {BACKBONE}", repo_dir)

    # Nếu feature branch đã tồn tại từ lần retry trước → xóa và tạo lại
    ok, _ = run(f"rev-parse --verify {branch_name}", repo_dir)
    if ok:
        run(f"branch -D {branch_name}", repo_dir)
        print(f"      [git] Deleted stale branch {branch_name}, recreating from {BACKBONE}")

    run(f"checkout -b {branch_name}", repo_dir)
    print(f"      [git] Feature branch ready (local): {branch_name} ← {BACKBONE}")


def commit_wip(repo_dir: str, branch: str, task_id: str, attempt: int) -> str:
    """
    Commit code hiện tại vào feature branch LOCAL sau mỗi lần dev agent chạy.
    Dùng cho WIP commits trong vòng lặp dev/retry.
    KHÔNG push. CI không chạy.

    Returns: "committed" | "nothing_to_commit"
    """
    # Verify đang trên đúng branch
    actual = current_branch(repo_dir)
    if actual != branch:
        print(f"      [git] WARNING: expected {branch}, got {actual} — switching")
        run(f"checkout {branch}", repo_dir)

    run("add -A", repo_dir)

    if not _has_staged_changes(repo_dir):
        print(f"      [git] Nothing to commit (attempt {attempt})")
        return "nothing_to_commit"

    ts = datetime.datetime.now().strftime("%H:%M:%S")
    msg = f"wip({task_id}): attempt {attempt} [{ts}]"
    ok, out = run(f'commit -m "{msg}"', repo_dir)
    if not ok:
        print(f"      [git] WIP commit failed: {out[:200]}")
        return "nothing_to_commit"

    print(f"      [git] WIP committed (local): attempt {attempt} on {branch}")
    return "committed"


def finalize_and_merge(
    repo_dir: str,
    branch: str,
    task_id: str,
    task_summary: str,
    component: str,
) -> bool:
    """
    Gọi khi TEST_PASS. Thực hiện:
      1. Squash toàn bộ WIP commits trên feature branch thành 1 commit sạch
      2. Merge --no-ff vào backbone LOCAL
      ── KHÔNG push ở đây ── push chỉ xảy ra khi toàn sprint kết thúc (push_backbone_to_origin)
      ── KHÔNG xóa feature branch ── giữ lại để debug/review, xóa manual khi cần

    Returns True nếu thành công, False nếu có lỗi.
    """
    print(f"\n      [git] Finalizing {task_id}...")

    # 1. Squash: đếm WIP commits vượt hơn backbone
    n_commits = _count_commits_ahead(repo_dir, BACKBONE, branch)
    if n_commits == 0:
        print(f"      [git] No commits ahead of {BACKBONE} — nothing to squash")
        return False
    if n_commits == 1:
        print(f"      [git] Single commit — skip squash, merge directly")
    else:
        # Soft reset về đầu backbone để gộp tất cả thay đổi vào staged area
        ok, out = run(f"reset --soft {BACKBONE}", repo_dir)
        if not ok:
            print(f"      [git] Squash reset failed: {out[:200]}")
            return False

        ts = datetime.datetime.now().strftime("%Y-%m-%d")
        squash_msg = f"feat({component}): {task_summary[:60]} [{task_id}] - {ts}"
        run("add -A", repo_dir)
        ok, out = run(f'commit -m "{squash_msg}"', repo_dir)
        if not ok:
            print(f"      [git] Squash commit failed: {out[:200]}")
            return False
        print(f"      [git] Squashed {n_commits} WIP commits → 1 clean commit")

    # 2. Merge vào backbone LOCAL
    run(f"checkout {BACKBONE}", repo_dir)
    merge_msg = f"merge({task_id}): {task_summary[:60]} into {BACKBONE}"
    ok, out = run(f'merge --no-ff {branch} -m "{merge_msg}"', repo_dir)
    if not ok:
        print(f"      [git] Merge into backbone failed: {out[:200]}")
        # Abort merge nếu bị conflict
        run("merge --abort", repo_dir)
        return False
    print(f"      [git] Merged {branch} → {BACKBONE} (local only — NOT pushed yet)")
    print(f"      [git] Feature branch kept: {branch} (delete manually when done)")

    # Push và xóa feature branch KHÔNG nằm ở đây.
    # Push toàn bộ backbone lên origin → gọi push_backbone_to_origin() sau khi sprint kết thúc.
    # Xóa feature branch → gọi delete_feature_branch() manual khi cần.

    return True


def push_backbone_to_origin(repo_dir: str) -> bool:
    """
    Push integration/current-sprint lên origin.
    Gọi 1 lần duy nhất sau khi TOÀN BỘ SPRINT kết thúc — CI trigger tại đây.
    KHÔNG gọi trong vòng lặp task.
    """
    _ensure_remote(repo_dir)

    # Đảm bảo đang đứng trên backbone trước khi push
    run(f"checkout {BACKBONE}", repo_dir)

    ok, out = run(f"push -u origin {BACKBONE}", repo_dir)
    if not ok and "non-fast-forward" in out:
        print(f"      [git] Non-fast-forward — retrying with --force-with-lease...")
        ok, out = run(f"push -u origin {BACKBONE} --force-with-lease", repo_dir)

    if ok:
        print(f"      [git] Pushed {BACKBONE} → origin ✓  (CI triggered — sprint complete)")
    else:
        print(f"      [git] Push failed: {out[:300]}")

    return ok


def delete_feature_branch(repo_dir: str, branch: str) -> None:
    """Xóa feature branch local sau khi đã merge."""
    actual = current_branch(repo_dir)
    if actual == branch:
        run(f"checkout {BACKBONE}", repo_dir)
    ok, out = run(f"branch -d {branch}", repo_dir)
    if not ok:
        # -d thất bại nếu branch chưa fully merged → dùng -D
        run(f"branch -D {branch}", repo_dir)
    print(f"      [git] Feature branch deleted: {branch}")


# ── Legacy / compat ────────────────────────────────────────────────────────────

def commit_and_push(repo_dir, branch, task, component):
    """
    DEPRECATED — dùng commit_wip() + finalize_and_merge() thay thế.
    Giữ lại để không break code cũ gọi hàm này.
    """
    print("      [git] WARNING: commit_and_push() is deprecated. "
          "Use commit_wip() during dev loop and finalize_and_merge() on TEST_PASS.")
    return commit_wip(repo_dir, branch, task.get("id", "UNKNOWN"), attempt=1)


def merge_to_develop(repo_dir, branch, task_id):
    """
    DEPRECATED — integration/current-sprint không merge vào develop trong pipeline.
    Develop nhận merge manual sau khi sprint kết thúc.
    """
    print("      [git] WARNING: merge_to_develop() is deprecated. "
          "Develop is only updated manually at end of sprint.")
    return False


def merge_incremental(repo_dir, feature_branch, push=False):
    """DEPRECATED — dùng finalize_and_merge()."""
    print("      [git] WARNING: merge_incremental() is deprecated.")
    return False


def prepare_feature_branch_compat(repo_dir, branch_name, base_branch=BACKBONE):
    """DEPRECATED alias — base_branch param ignored, always uses BACKBONE."""
    return prepare_feature_branch(repo_dir, branch_name)

def abort_to_backbone(repo_dir: str) -> None:
    """
    Dọn dẹp khi dev fail — quay về backbone để task tiếp theo không bị nhiễm.
    Thay thế _back_to_develop() trong flow mới.
    KHÔNG xóa feature branch — orchestrator giữ lại để debug nếu cần.
    """
    ok, _ = run(f"checkout {BACKBONE}", repo_dir)
    if not ok:
        run("checkout develop", repo_dir)  # hard fallback
        
# Legacy alias
def checkout_or_create_branch(repo_dir, branch):
    return prepare_feature_branch(repo_dir, branch)