"""
Git Operations - tach biet khoi adapter de de swap (GitHub / GitLab / local).
"""
import os
import subprocess
import datetime
import re

# ================================================================
# ĐỔI URL NÀY THÀNH REPO CỦA BẠN
REMOTE_URL = "https://github.com/gnudevx/pos-app-test_v2.git"
# Nếu dùng token (recommended để tránh nhập password):
# REMOTE_URL = "https://ghp_YOUR_TOKEN@github.com/gnudevx/pos-app-test_v2.git"
# ================================================================


def make_branch_name(task_id: str, summary: str) -> str:
    slug = summary.lower()
    slug = re.sub(r'[^a-z0-9\s-]', '', slug)
    slug = re.sub(r'\s+', '-', slug.strip())
    slug = re.sub(r'-+', '-', slug)
    slug = slug[:40].rstrip('-')
    return f"feature/{task_id.lower()}-{slug}"


def run(cmd, cwd):
    result = subprocess.run(
        f"git {cmd}",
        shell=True, capture_output=True, text=True,
        cwd=cwd, encoding="utf-8", errors="ignore",
    )
    return result.returncode == 0, (result.stdout + result.stderr).strip()


def _ensure_remote(repo_dir):
    ok, stdout = run("remote get-url origin", repo_dir)
    if ok and stdout.strip():
        return True
    ok, out = run(f"remote add origin {REMOTE_URL}", repo_dir)
    if ok:
        print(f"      [git] Remote added: {REMOTE_URL}")
    else:
        print(f"      [git] Failed to add remote: {out}")
    return ok


def init_repo_if_needed(repo_dir):
    """Tạo initial commit trên develop nếu repo chưa có commit nào."""
    os.makedirs(repo_dir, exist_ok=True)

    if not os.path.exists(os.path.join(repo_dir, ".git")):
        run("init", repo_dir)
        run('config user.email "dev-agent@pos-pipeline.local"', repo_dir)
        run('config user.name "POS Dev Agent"', repo_dir)

    result = subprocess.run(
        ["git", "log", "--oneline", "-1"],
        cwd=repo_dir, capture_output=True, text=True
    )
    if result.returncode != 0 or not result.stdout.strip():
        print("[git] Repo trống — tạo initial commit trên develop...")
        run("checkout -b develop", repo_dir)
        readme = os.path.join(repo_dir, "README.md")
        with open(readme, "w") as f:
            f.write("# POS App\nGenerated by POS Pipeline.\n")
        run("add -A", repo_dir)
        run('commit -m "chore: initial commit"', repo_dir)
        print("[git] Initial commit created on develop")
        _ensure_remote(repo_dir)
        ok, out = run("push -u origin develop", repo_dir)
        if ok:
            print("[git] develop pushed to origin")
        else:
            print(f"[git] Push develop failed: {out[:200]}")
    else:
        print("[git] Repo đã có commit, bỏ qua init")
        _ensure_remote(repo_dir)


def prepare_feature_branch(repo_dir, branch):
    """
    Checkout feature branch TRƯỚC khi dev-agent ghi file.
    *** Gọi hàm này TRƯỚC khi Gemini generate + ghi file ***
    """
    os.makedirs(repo_dir, exist_ok=True)

    # Về develop sạch
    run("checkout develop", repo_dir)
    run("reset --hard HEAD", repo_dir)
    run("clean -fd", repo_dir)

    # Xóa branch cũ nếu có (retry scenario)
    run(f"branch -D {branch}", repo_dir)

    # Tạo feature branch mới từ develop
    ok, out = run(f"checkout -b {branch}", repo_dir)
    if not ok:
        raise RuntimeError(f"Cannot create branch: {branch}\n{out}")

    print(f"      [git] On branch: {branch}")
    return branch


def commit_and_push(repo_dir, branch, task, component):
    """
    Commit tất cả files đang trên feature branch và push.
    *** Gọi SAU KHI đã ghi xong file (prepare_feature_branch đã gọi trước) ***
    """
    # Verify đang trên đúng branch
    _, current = run("rev-parse --abbrev-ref HEAD", repo_dir)
    if current.strip() != branch:
        print(f"      [git] WARNING: expected {branch}, got {current} — switching")
        run(f"checkout {branch}", repo_dir)

    # Stage tất cả
    run("add -A", repo_dir)

    # Check có staged changes không
    _, diff_out = run("diff --cached --stat", repo_dir)
    if not diff_out.strip():
        print(f"      [git] Nothing new to commit on {branch}")
        _back_to_develop(repo_dir)
        return "no_diff"

    # Commit
    ts = datetime.datetime.now().strftime("%Y-%m-%d")
    msg = f'feat({component}): {task["summary"][:50]} [{task["id"]}] - {ts}'
    ok, out = run(f'commit -m "{msg}"', repo_dir)
    if not ok:
        print(f"      [git] Commit failed: {out[:200]}")
        _back_to_develop(repo_dir)
        return "no_diff"

    print(f"      [git] Committed on {branch}")
    _ensure_remote(repo_dir)

    # Push feature branch
    ok, push_out = run(f"push -u origin {branch}", repo_dir)
    if not ok and "non-fast-forward" in push_out:
        print(f"      [git] Non-fast-forward — retrying with --force-with-lease...")
        ok, push_out = run(f"push -u origin {branch} --force-with-lease", repo_dir)
    
    _back_to_develop(repo_dir)

    if ok:
        print(f"      [git] Pushed: {branch} → origin ✓")
        return "pushed"
    else:
        print(f"      [git] Push failed: {push_out[:300]}")
        print(f"      [git] Tip: thêm token vào REMOTE_URL trong git_ops.py")
        return "no_remote"


def merge_to_develop(repo_dir, branch, task_id):
    """Merge feature branch vào develop và push."""
    run("checkout develop", repo_dir)
    ok, out = run(f'merge --no-ff {branch} -m "merge: {task_id} into develop"', repo_dir)
    if not ok:
        print(f"    [MERGE] Merge failed: {out[:200]}")
        return False
    ok, out = run("push origin develop", repo_dir)
    if ok:
        print(f"    [MERGE] develop pushed to origin ✓")
    else:
        print(f"    [MERGE] Push develop failed: {out[:200]}")
    return ok


def current_branch(repo_dir):
    _, stdout = run("rev-parse --abbrev-ref HEAD", repo_dir)
    return stdout.strip()


def _back_to_develop(repo_dir):
    ok, _ = run("checkout develop", repo_dir)
    if not ok:
        run("checkout main", repo_dir)


# Legacy alias
def checkout_or_create_branch(repo_dir, branch):
    return prepare_feature_branch(repo_dir, branch)